---
- name: Install Java on Ubuntu and Amazon Linux
  hosts: webservers
  become: yes

  tasks:

    - name: Install Java on Debian family
      apt:
        name: default-jdk
        state: present
      when: ansible_os_family == "Debian"

    - name: Install Java on RedHat family
      yum:
        name: java-1.8.0-openjdk
        state: present
      when: ansible_os_family == "RedHat"
